export const editFlightDefaultValues = {
  id: '',
  departureAirport: null,
  arrivalAirport: null,
  airline: null,
  aircraftType: null,
  flightNumber: null,
  callsign: '',
  tailNumber: '',
  outDateISO: '',
  outTimeValue: '',
  inTimeValue: '',
  class: null,
  seatNumber: '',
  seatPosition: null,
  reason: null,
  comments: '',
  trackingLink: '',
};
