export const editFlightDefaultValues = {
  id: '',
  departureAirportId: '',
  arrivalAirportId: '',
  airlineId: '',
  aircraftTypeId: '',
  flightNumber: null,
  callsign: '',
  tailNumber: '',
  outDateISO: '',
  outTimeValue: '',
  inTimeValue: '',
  class: null,
  seatNumber: '',
  seatPosition: null,
  reason: null,
  comments: '',
  trackingLink: '',
};
