export const addFlightDefaultValues = {
  departureAirport: null,
  arrivalAirport: null,
  airline: null,
  aircraftType: null,
  flightNumber: null,
  tailNumber: '',
  airframe: null,
  outDateISO: '',
  outTimeValue: '',
  inTimeValue: '',
  class: null,
  seatNumber: '',
  seatPosition: null,
  reason: null,
  comments: '',
  trackingLink: '',
};
