export const addFlightDefaultValues = {
  departureAirportId: '',
  arrivalAirportId: '',
  airlineId: '',
  aircraftTypeId: '',
  flightNumber: null,
  callsign: '',
  tailNumber: '',
  outDate: '',
  outTime: '',
  offTime: null,
  onTime: null,
  inTime: '',
  class: null,
  seatNumber: '',
  seatPosition: null,
  reason: null,
  comments: '',
  trackingLink: '',
};
